// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgtycpcnobkbfolkhobk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndHljcGNub2JrYmZvbGtob2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMTU5MTAsImV4cCI6MjA1Nzc5MTkxMH0.3jtCivr5HhBa2N_EErjWLUHrebhP6DbbXKXeJkwIeUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);